sudo: required

env:
  global:
  - OPENSHIFT_VERSION=3.6.1
  - OPENSHIFT_COMMIT=008f2d5 # always update when bumping $OPENSHIFT_VERSION
  - DOCKER_USER=projectoddbot
  - secure: "RqSXO/Odxdc8FJQIZml8azjuwYPvxR9RHK/vNR3pbNuKmGkmgqkXs61tZrdpGIYVeBUhVoHqmuk9RN9Q8nrXFTjp7C2GbneZESUFF4NElQcYLokhNDXXbQHARyiBJFlaiBFvXDJTmKBBBuiEVOHaZXOKcJIno9dLaB+H9XmNTuZx4PvUAUHLnqdvRU9ri/eeEP0u+BVPJsVRMGQY6oTTR0yaXuUg4oVXV+nDsoHoUle1vpcvMsHU0frOc1BdFbk01mGycpEgZ35Jwh964D86YKJg/FFnFZwWKtdWU7PibTiRdy2wUFoAL6MHi/DtnQKTuxDavBPj0O8WHtqHL5WKao43hHnmDtludXFto80bWRTDx1Z9NdC8vCd0Ib998oVZOIbDgXe6geQH+rnY6kbXiecS3CJwEuuJ4/T2A6YGgAB+woJ971Yj1ig7EaH0dH/hg0tEp33SKhlkXChe5+K2Bf3MCnTd34wmMpAGlbCSiNYafNBg01hYjQxrb+c9cYBqkVIzr5R3b9asjtl4JyBpoOk0GWu65VJApSScOznagKNXw8/ojsG69bJzh2BFjXYJjFPfY1mFRlPyg2D3frXGkoNBXI3TaiKGzU+KolXHNbR2eGqKXeVFdK2hhe0CCq/uepNuz5JukqTlGVgSupwne9+9LIeQci573I7XoPblvnU="
  matrix:
  - OPENSHIFT_TEMPLATE=template.yml
  - OPENSHIFT_TEMPLATE=persistent-template.yml

services:
  - docker

before_install:
  - ./tools/travis/setupscan.sh
  - ./tools/travis/setup.sh

script:
  - ./tools/travis/scancode.sh
  - ./tools/travis/build.sh "PROJECTODD_VERSION=openshift-latest WHISK_ACTIONS_INVOKES_CONCURRENT=666"
  - ./tools/travis/test.sh

after_failure:
  - ./tools/travis/collect-logs.sh

stages:
  - docker build
  - test
  - deploy

jobs:
  include:
    - stage: docker build
      env: OPENSHIFT_TEMPLATE=template.yml
      before_install: skip
      script: ./tools/travis/publish.sh openshift-latest
    - stage: deploy
      env: OPENSHIFT_TEMPLATE=template.yml
      before_install: skip
      script: ./tools/travis/publish.sh
